### ISSUE TITLE
Projects tab: Information about ocrd_all releases

### ISSUE THREAD

**Issue by mweidling** [OCR-D/kwalitee-dashboard-back-end#5]
The "Projects" tab should hold information about which projects are part of the latest ocrd_all release–and which are not. This information has to be provided within the `repos.json` (or a separate JSON file).

**Comment by mweidling** [comment]
As discussed in our last meeting (2022-06-01) I propose to have a separate file that holds the information about the ocrd_all releases. I have a structure like this in mind:

```json
[
    {
        "tag": "v2022-05-04",
        "projects":
            [
                "https://github.com/OCR-D/core",
                "https://github.com/qurator-spk/eynollah",
                "https://github.com/cisocrgroup/ocrd_cis",
                "https://github.com/bertsky/ocrd_detectron2",
                "https://github.com/bertsky/ocrd_doxa",
                "https://github.com/OCR-D/ocrd_fileformat",
                "https://github.com/OCR-D/ocrd_keraslm",
                "https://github.com/OCR-D/ocrd_segment",
                "https://github.com/skvark/opencv-python",
                "https://github.com/qurator-spk/sbb_binarization",
                "https://github.com/bertsky/workflow-configuration"
            ]
    },
    {
        "tag": "asdf",
        "projects":
            [
                "..."
            ]
    }
]
```

@paulpestov Is this something you can work with and that satisfies our needs?

**Comment by paulpestov** [comment]
Thx! Here a suggestion:

Having keys for the sections and arrays as their values. This way we can identiy the data easier on the frontend:
```json 
{
    "orcd_all_releases": [
        { 
            "tag": "v2022-05-04",
           // ...
        }, 
        { 
            "tag": "v2021-02-01",
           // ...
        }
    ],
    "projects": [
        { 
            "tag": "asdf",
           // ...
        }, 
        { 
            "tag": "1234",
           // ...
        }
    ],
}
```

Also a question, should the project ID be the URL? A separate `url` key might be better, but let's see.

**Comment by mweidling** [comment]
# Requirements for this feature

- information about which projects are part of an ocrd_all release
- each project should be listed only once – in the latest ocrd_all release it is part of. older releases should be tossed.
